package ifi.demo.model;
// Generated Oct 24, 2017 5:59:32 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Problems generated by hbm2java
 */
@Entity
@Table(name = "problems", catalog = "servicecalls")
public class Problems implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String problemCode;
	private String egNoResponse;
	private String problemDescription;
	private Set<ServiceRequestCalls> serviceRequestCallses = new HashSet<ServiceRequestCalls>(0);

	public Problems() {
	}

	public Problems(String problemCode, String egNoResponse, String problemDescription) {
		this.problemCode = problemCode;
		this.egNoResponse = egNoResponse;
		this.problemDescription = problemDescription;
	}

	public Problems(String problemCode, String egNoResponse, String problemDescription,
			Set<ServiceRequestCalls> serviceRequestCallses) {
		this.problemCode = problemCode;
		this.egNoResponse = egNoResponse;
		this.problemDescription = problemDescription;
		this.serviceRequestCallses = serviceRequestCallses;
	}

	@Id

	@Column(name = "problem_code", unique = true, nullable = false, length = 50)
	public String getProblemCode() {
		return this.problemCode;
	}

	public void setProblemCode(String problemCode) {
		this.problemCode = problemCode;
	}

	@Column(name = "eg_no_response", nullable = false, length = 50)
	public String getEgNoResponse() {
		return this.egNoResponse;
	}

	public void setEgNoResponse(String egNoResponse) {
		this.egNoResponse = egNoResponse;
	}

	@Column(name = "problem_description", nullable = false)
	public String getProblemDescription() {
		return this.problemDescription;
	}

	public void setProblemDescription(String problemDescription) {
		this.problemDescription = problemDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "problems")
	@JsonIgnore
	public Set<ServiceRequestCalls> getServiceRequestCallses() {
		return this.serviceRequestCallses;
	}

	public void setServiceRequestCallses(Set<ServiceRequestCalls> serviceRequestCallses) {
		this.serviceRequestCallses = serviceRequestCallses;
	}

}
