package ifi.demo.model;
// Generated Oct 24, 2017 5:59:32 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ServiceRequestActions generated by hbm2java
 */
@Entity
@Table(name = "service_request_actions", catalog = "servicecalls")
public class ServiceRequestActions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer responseId;
	private Actions actions;
	private OutcomeCodes outcomeCodes;
	private ServiceRequestCalls serviceRequestCalls;
	private Technicians technicians;
	private String responseDateTime;

	public ServiceRequestActions() {
	}

	public ServiceRequestActions(String responseDateTime) {
		this.responseDateTime = responseDateTime;
	}

	public ServiceRequestActions(Actions actions, OutcomeCodes outcomeCodes, ServiceRequestCalls serviceRequestCalls,
			Technicians technicians, String responseDateTime) {
		this.actions = actions;
		this.outcomeCodes = outcomeCodes;
		this.serviceRequestCalls = serviceRequestCalls;
		this.technicians = technicians;
		this.responseDateTime = responseDateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "response_id", unique = true, nullable = false)
	public Integer getResponseId() {
		return this.responseId;
	}

	public void setResponseId(Integer responseId) {
		this.responseId = responseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "action_code")
	public Actions getActions() {
		return this.actions;
	}

	public void setActions(Actions actions) {
		this.actions = actions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "outcome_code")
	public OutcomeCodes getOutcomeCodes() {
		return this.outcomeCodes;
	}

	public void setOutcomeCodes(OutcomeCodes outcomeCodes) {
		this.outcomeCodes = outcomeCodes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "call_id")
	public ServiceRequestCalls getServiceRequestCalls() {
		return this.serviceRequestCalls;
	}

	public void setServiceRequestCalls(ServiceRequestCalls serviceRequestCalls) {
		this.serviceRequestCalls = serviceRequestCalls;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "technician_id")
	public Technicians getTechnicians() {
		return this.technicians;
	}

	public void setTechnicians(Technicians technicians) {
		this.technicians = technicians;
	}

	@Column(name = "response_date_time", nullable = false, length = 50)
	public String getResponseDateTime() {
		return this.responseDateTime;
	}

	public void setResponseDateTime(String responseDateTime) {
		this.responseDateTime = responseDateTime;
	}

}
