package ifi.demo.model;
// Generated Oct 24, 2017 5:59:32 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * StatusCodes generated by hbm2java
 */
@Entity
@Table(name = "status_codes", catalog = "servicecalls")
public class StatusCodes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String statusCode;
	private String egCompleteorwip;
	private String statusDescription;
	private Set<ServiceRequestCalls> serviceRequestCallses = new HashSet<ServiceRequestCalls>(0);

	public StatusCodes() {
	}

	public StatusCodes(String statusCode, String egCompleteorwip, String statusDescription) {
		this.statusCode = statusCode;
		this.egCompleteorwip = egCompleteorwip;
		this.statusDescription = statusDescription;
	}

	public StatusCodes(String statusCode, String egCompleteorwip, String statusDescription,
			Set<ServiceRequestCalls> serviceRequestCallses) {
		this.statusCode = statusCode;
		this.egCompleteorwip = egCompleteorwip;
		this.statusDescription = statusDescription;
		this.serviceRequestCallses = serviceRequestCallses;
	}

	@Id

	@Column(name = "status_code", unique = true, nullable = false, length = 50)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "eg_completeorwip", nullable = false, length = 50)
	public String getEgCompleteorwip() {
		return this.egCompleteorwip;
	}

	public void setEgCompleteorwip(String egCompleteorwip) {
		this.egCompleteorwip = egCompleteorwip;
	}

	@Column(name = "status_description", nullable = false)
	public String getStatusDescription() {
		return this.statusDescription;
	}

	public void setStatusDescription(String statusDescription) {
		this.statusDescription = statusDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusCodes")
	@JsonIgnore
	public Set<ServiceRequestCalls> getServiceRequestCallses() {
		return this.serviceRequestCallses;
	}

	public void setServiceRequestCallses(Set<ServiceRequestCalls> serviceRequestCallses) {
		this.serviceRequestCallses = serviceRequestCallses;
	}

}
