package ifi.demo.model;
// Generated Oct 24, 2017 5:59:32 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Technicians generated by hbm2java
 */
@Entity
@Table(name = "technicians", catalog = "servicecalls")
public class Technicians implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer technicianId;
	private String egBobbyCaldwell;
	private String technicianName;
	private Set<ServiceRequestActions> serviceRequestActionses = new HashSet<ServiceRequestActions>(0);

	public Technicians() {
	}

	public Technicians(String egBobbyCaldwell, String technicianName) {
		this.egBobbyCaldwell = egBobbyCaldwell;
		this.technicianName = technicianName;
	}

	public Technicians(String egBobbyCaldwell, String technicianName,
			Set<ServiceRequestActions> serviceRequestActionses) {
		this.egBobbyCaldwell = egBobbyCaldwell;
		this.technicianName = technicianName;
		this.serviceRequestActionses = serviceRequestActionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "technician_id", unique = true, nullable = false)
	public Integer getTechnicianId() {
		return this.technicianId;
	}

	public void setTechnicianId(Integer technicianId) {
		this.technicianId = technicianId;
	}

	@Column(name = "eg_bobby_caldwell", nullable = false, length = 50)
	public String getEgBobbyCaldwell() {
		return this.egBobbyCaldwell;
	}

	public void setEgBobbyCaldwell(String egBobbyCaldwell) {
		this.egBobbyCaldwell = egBobbyCaldwell;
	}

	@Column(name = "technician_name", nullable = false, length = 50)
	public String getTechnicianName() {
		return this.technicianName;
	}

	public void setTechnicianName(String technicianName) {
		this.technicianName = technicianName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "technicians")
	@JsonIgnore
	public Set<ServiceRequestActions> getServiceRequestActionses() {
		return this.serviceRequestActionses;
	}

	public void setServiceRequestActionses(Set<ServiceRequestActions> serviceRequestActionses) {
		this.serviceRequestActionses = serviceRequestActionses;
	}

}
